name: sitemap_scraping

# Controls when the action will run.
on:
  schedule:
    - cron:  '0 * * * *'


jobs: 
  autoscrape:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Load repo and install R
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master

    # Set-up R
      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("sf")'
          R -e 'install.packages("data.table")'
          R -e 'install.packages("downloader")'
          R -e 'install.packages("utils")'
    # Run R script
      - name: Generate data
          run:|
          source("R/Telecharger_NAIADES.R")
          shell:Rscript {0} 
      
 # Add new files in data folder, commit along with other modified files, push
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "NAIADES $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
